### ISSUE TITLE
Debian install dua error

### ISSUE THREAD

**Issue by zhangsan6661** [Byron/dua-cli#127] opened 2022-05-12 10:57 UTC
readme file  other linux version script error

raw sample:
curl -LSfs https://raw.githubusercontent.com/byron/dua-cli/master/ci/install.sh | \
    sh -s -- --git byron/dua-cli --target x86_64-unknown-linux-musl --crate dua

first: path lower byron.
     can't find path 404
     byron/dua-cli ====> Byron/dua-cli  

second:  release version can't find latest path

     curl -LSfs https://raw.githubusercontent.com/byron/dua-cli/master/ci/install.sh | \
    sh -s -- --git byron/dua-cli --target x86_64-unknown-linux-musl --crate dua

=====>OK
     curl -LSfs https://raw.githubusercontent.com/byron/dua-cli/master/ci/install.sh | \
    sh -s -- --git Byron/dua-cli --target x86_64-unknown-linux-musl  --tag  v2.17.4  --crate dua

**Comment by Byron** [comment] 2022-05-13 00:01
The instructions in the README changed to compensate:

```
curl -LSfs https://raw.githubusercontent.com/byron/dua-cli/master/ci/install.sh | \
    sh -s -- --git byron/dua-cli --crate dua --tag v2.17.2
```

I didn't get around fixing the install script after GitHub broke it apparently, and would love to have an alternative alltogether.

**Comment by Byron** [comment] 2022-05-13 00:02
Closing as the issue is fixed in the README.

**Closed by Byron** 2022-05-13 00:02 UTC

**Comment by zhangsan6661** [comment] 2022-05-13 01:37
--git byron/dua-cli   
--git Byron/dua-cli   


repository name fist letter is Upper , when lower  url will happen 404

**Comment by zhangsan6661** [comment] 2022-05-13 01:41
![Xnip2022-05-13_09-38-53](https://user-images.githubusercontent.com/8611544/168194308-b213f343-fc35-4d86-a4f5-9aaa51e8d890.png)


release version tag update latest also  ok
dua-latest-x86_64-unknown-linux-musl.tar.gz

**Comment by Byron** [comment] 2022-05-13 03:59
Thanks a lot for pointing this out! It's amazing that this ever work, maybe it's a change on GitHub, who knows. 

I have adjusted the script once again, but but `--tag latest` didn't work for me at all. Am I missing something? It would be great not to be able to avoid hardcoding a version.
